mieweb/wikiGDrive

.eslintignore, .eslintrc, .jsbeautifyrc, .vscode/settings.json, package-lock.json, package.json, src/ConfigService.js, src/FileService.js, src/GoogleAuthService.js, src/GoogleDocsService.js, src/GoogleDriveService.js, src/HttpClient.js, src/LinkTransform.js, src/MarkDownConverter.js, src/SyncService.js, src/TocGenerator.js, src/index.js, webpack.config.js
Closes: #4 
Changed jscs to eslint
Added style rules for eslint / jsbeautify
Removed some unnecessary escaping
Fixed a bug where fontFamily would cause a crash
Commented out some unused code past a return
Changed while(true) to a setInterval promise loop for --watch
=> Some cleanup and move to ESlint

src/FrontMatterTransform.js, src/LinkTranslator.js, src/MarkDownTransform.js, src/SyncService.js
=> Fix lists numbering and paragraphs

src/GoogleDriveService.js
This api request was missing two params needed in order to see changes from shared drive.
=> Added params needed to watch shared drives

README.md, src/GoogleDriveService.js, src/SyncService.js, src/index.js
=> Add support for team/shared drive

src/MarkDownTransform.js
=> Fix table cell lists

package.json
https://github.com/mieweb/wikiGDrive/commit/452dd917dfb257520d000315fb13bfbdd8760160
=> Fixed whitespace in tables breaking markdown

src/plugins/GitPlugin.js, src/utils/parseSecondsInterval.js, test/ParseSecondsIntervalTest.js
=> Extract parseSecondsInterval function

src/google/GoogleDriveService.ts
=> Fix fields query to include nextPageToken

src/google/GoogleDriveService.ts, src/plugins/DownloadPlugin.ts, src/plugins/FilesStructurePlugin.ts, src/plugins/TransformPlugin.ts, src/storage/FilesStructure.ts, test/FilesStructureTest.js
=> Dev/raw html closes #110 #111 

src/plugins/TransformPlugin.ts
=> Fix TOC generation

src/plugins/WatchChangesPlugin.ts
Making verbose "No changes detected. Sleeping for 10 seconds."
=> Making timeouts/sleeps output as debug

src/generateNavigationHierarchy.ts, test/nav/NavigationExtractTest.ts, test/nav/nav.json
=> Fix navigation paragraph bug

src/html/EmbedImageFixer.ts, src/plugins/StatusPlugin.ts, src/storage/DownloadFilesStorage.ts, src/utils/ImageUnZipper.ts, src/utils/UnZipper.ts, src/utils/extractDocumentLinks.ts, src/utils/idParsers.ts
=> Fix image linking and extracting

src/plugins/TransformPlugin.ts, src/storage/LocalFilesStorage.ts, src/storage/LocalPathGenerator.ts, test/LocalFilesTest.ts
=> Fix folder renaming:

src/plugins/GoogleApiPlugin.ts, src/progress/ProgressPlugin.ts
=> Fix prompt for user google code while authenticating

README.md
=> Removed david-dm.org from README

app_script/Code.gs
https://script.google.com/a/mieweb.com/d/1yT4CrPDqFCbPxHEUO-pYs6f2BZiNIYeo4ZRJSM_qb3nsLew5GTpXbvWK/edit
=> update wikigdrive AddOn

apps/ui/assets/mie.css, apps/ui/src/components/ChangesViewer.vue, apps/ui/src/components/FilePreview.vue, apps/ui/src/components/LogsViewer.vue, apps/ui/src/components/MarkDown.vue, apps/ui/src/components/PreviewHeader.vue, apps/ui/src/components/ShareModal.vue, apps/ui/src/components/prismFix.ts, apps/ui/src/pages/FolderView.vue, apps/ui/src/pages/GDocsView.vue, src/containers/google_folder/GoogleFolderContainer.ts, src/containers/google_folder/QueueDownloader.ts, src/containers/google_folder/QueueTask.ts, src/containers/job/JobManagerContainer.ts, src/containers/server/SocketManager.ts, src/containers/transform/DirectoryScanner.ts, src/containers/transform/LocalFilesGenerator.ts, src/containers/transform/QueueTransformer.ts, src/containers/transform/TaskLocalFileTransform.ts, src/containers/transform/TransformContainer.ts
Resolves #361
Resolves #343
Resolves #354
=> GitHub bugs

src/containers/transform/MarkdownTreeProcessor.ts
Possible fix for empty https://wikigdrive.com/drive/0APmwe3yIhGabUk9PVA
=> Fix tree version

apps/ui/src/components/GitCommit.vue
=> Add removed files to git commit

.github/workflows/create-release.yml, .github/workflows/dev-pr-close.yml, .github/workflows/dev-pr-label.yml, .github/workflows/dev-pr-open.yml, .github/workflows/npmpublish.yml, package.json, website/docs/developer-guide.md
=> Update developer-guide.md to describe version strategy

src/utils/idParsers.ts
Resolves: https://github.com/mieweb/docs/issues/41
Add capability to parse: `https://docs.google.com/document/u/0/d/14JVn4bPROs7udlR_yiBOs2oxpQKGjrTqzotYL4zx5PA/edit`
=> Improve google url parser

.github/workflows/dev-pr-close.yml
https://github.com/mieweb/wikiGDrive/issues/297
=> Fix GH_ORG_EMAIL typo

apps/ui/src/components/UtilsMixin.ts
=> GitHub button in git_commit window link directly to active page

Dockerfile, deno.json, deno.lock, src/LinkTranslator.ts, src/containers/action/dockerProxy.ts, src/containers/job/worker.ts, src/containers/transform/TaskLocalFileTransform.ts, src/odt/executeOdtToMarkdown.ts, website/public/assets/layout.css
=> Revert "Develop 10/16/25"
